export const JSONL_TYPES = [
  "query",
  "react",
  "plan-execute",
  "submit",
  "planning",
  "event",
  "steer",
  "system",
  "step"
] as const;

export const ROLES = ["user", "assistant", "system", "tool"] as const;

export const STREAM_EVENT_TYPES = [
  "request.query",
  "awaiting.ask",
  "awaiting.answer",
  "request.submit",
  "request.steer",
  "chat.start",
  "run.start",
  "debug.preCall",
  "debug.postCall",
  "usage.snapshot",
  "memory.write",
  "memory.read",
  "memory.search",
  "memory.update",
  "memory.forget",
  "memory.timeline",
  "memory.promote",
  "memory.consolidate",
  "run.complete",
  "run.cancel",
  "run.error",
  "reasoning.start",
  "reasoning.delta",
  "reasoning.end",
  "reasoning.snapshot",
  "content.start",
  "content.delta",
  "content.end",
  "content.snapshot",
  "tool.start",
  "tool.args",
  "tool.end",
  "tool.snapshot",
  "tool.result",
  "source.publish",
  "action.start",
  "action.args",
  "action.end",
  "action.snapshot",
  "action.result",
  "plan.create",
  "plan.update",
  "planning.delta",
  "planning.snapshot",
  "task.start",
  "task.complete",
  "task.cancel",
  "task.error",
  "artifact.publish"
] as const;

export const TERMINAL_EVENTS = ["run.complete", "run.cancel", "run.error"] as const;
export const WS_FRAMES = ["request", "response", "stream", "push", "error"] as const;

export const EVENT_PAYLOAD_SCHEMAS: Record<string, Record<string, string>> = {
  "request.query": { requestId: "string", chatId: "string", role: "string", message: "string", agentKey: "string", teamId: "string", references: "any", params: "any", scene: "any", stream: "boolean" },
  "awaiting.ask": { awaitingId: "string", mode: "string", viewportType: "string", viewportKey: "string", timeout: "number", runId: "string", agentKey: "string", questions: "array", approvals: "array", forms: "array", plan: "any" },
  "awaiting.answer": { awaitingId: "string", mode: "string", status: "string", submitId: "string", answers: "any", approvals: "array", forms: "array", plan: "any", error: "string" },
  "request.submit": { requestId: "string", chatId: "string", runId: "string", awaitingId: "string", submitId: "string", params: "any" },
  "request.steer": { requestId: "string", chatId: "string", runId: "string", steerId: "string", message: "string", role: "string" },
  "chat.start": { chatId: "string", chatName: "string" },
  "run.start": { runId: "string", chatId: "string", agentKey: "string" },
  "debug.preCall": { runId: "string", chatId: "string", data: "any" },
  "debug.postCall": { runId: "string", chatId: "string", data: "any" },
  "usage.snapshot": { runId: "string", chatId: "string", taskId: "string", model: "string", contextWindow: "any", usage: "any" },
  "run.complete": { runId: "string", finishReason: "string", usage: "any" },
  "run.cancel": { runId: "string", usage: "any" },
  "run.error": { runId: "string", error: "string", usage: "any" },
  "reasoning.start": { reasoningId: "string", runId: "string", taskId: "string", reasoningLabel: "string" },
  "reasoning.delta": { reasoningId: "string", delta: "string" },
  "reasoning.end": { reasoningId: "string" },
  "reasoning.snapshot": { reasoningId: "string", runId: "string", text: "string", taskId: "string", reasoningLabel: "string" },
  "content.start": { contentId: "string", runId: "string", taskId: "string" },
  "content.delta": { contentId: "string", delta: "string" },
  "content.end": { contentId: "string" },
  "content.snapshot": { contentId: "string", runId: "string", text: "string", taskId: "string" },
  "tool.start": { toolId: "string", runId: "string", taskId: "string", toolName: "string", toolLabel: "string", toolDescription: "string" },
  "tool.args": { toolId: "string", delta: "string", chunkIndex: "number" },
  "tool.end": { toolId: "string" },
  "tool.snapshot": { toolId: "string", runId: "string", toolName: "string", taskId: "string", toolLabel: "string", toolDescription: "string", arguments: "string" },
  "tool.result": { toolId: "string", result: "any", hitl: "any" },
  "source.publish": { publishId: "string", runId: "string", taskId: "string", toolId: "string", kind: "string", query: "string", sourceCount: "number", chunkCount: "number", sources: "array" },
  "action.start": { actionId: "string", runId: "string", taskId: "string", actionName: "string", description: "string" },
  "action.args": { actionId: "string", delta: "string" },
  "action.end": { actionId: "string" },
  "action.snapshot": { actionId: "string", runId: "string", actionName: "string", taskId: "string", description: "string", arguments: "string" },
  "action.result": { actionId: "string", result: "any" },
  "plan.create": { planId: "string", chatId: "string", plan: "any" },
  "plan.update": { planId: "string", chatId: "string", plan: "any" },
  "planning.delta": { planningId: "string", delta: "string" },
  "planning.snapshot": { planningId: "string", planningFile: "string", chatId: "string", runId: "string", text: "string" },
  "task.start": { taskId: "string", runId: "string", taskName: "string", description: "string", subAgentKey: "string", invokingToolId: "string" },
  "task.complete": { taskId: "string" },
  "task.cancel": { taskId: "string", reason: "string" },
  "task.error": { taskId: "string", error: "string" },
  "artifact.publish": { chatId: "string", runId: "string", artifactCount: "number", artifacts: "array" }
};
